# apiVersion: fluentd.fluent.io/v1alpha1
# kind: Fluentd
# metadata:
#   name: fluentd
#   namespace: fluent
#   labels:
#     app.kubernetes.io/name: fluentd
# spec:
#   globalInputs:
#   - forward: 
#       bind: 0.0.0.0
#       port: 24224
#   replicas: 1 
#   image: kubesphere/fluentd:v1.14.4
#   fluentdCfgSelector: 
#     matchLabels:
#       config.fluentd.fluent.io/enabled: "true"
# ---
apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: fluentd-http
  namespace: fluent
  labels:
    app.kubernetes.io/name: fluentd
spec:
  globalInputs:
    - http: 
        bind: 0.0.0.0
        port: 9880
  replicas: 1
  image: kubesphere/fluentd:v1.14.4
  fluentdCfgSelector: 
    matchLabels:
      config.fluentd.fluent.io/mode: "fluentd-only" 
  logLevel: debug
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: FluentdConfig
metadata:
  name: fluentd-only-config
  namespace: fluent
  labels:
    config.fluentd.fluent.io/mode: "fluentd-only" 
spec:
  outputSelector:
    matchLabels:
      output.fluentd.fluent.io/mode: "fluentd-only"
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: Output
metadata:
  name: fluentd-only-stdout
  namespace: fluent
  labels:
    output.fluentd.fluent.io/mode: "fluentd-only"
spec: 
  outputs: 
  - stdout: {}
    logLevel: debug
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: Output
metadata:
  name: fluentd-only-kafka
  namespace: fluent
  labels:
    output.fluentd.fluent.io/mode: "fluentd-only"
spec:
  outputs:
  - kafka:
      brokers:  "my-cluster-kafka-bootstrap:9092"
      topicKey: nil
      defaultTopic: test
      useEventTime: true
      requiredAcks: -1
      compressionCodec: gzip
    format:
      type: json
    buffer:
      tag: topic
      type: file
      path: /var/log/td-agent/buffer/td
      flushInterval: 1s
    logLevel: debug
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: fluentd-output-kafka-2
  labels:
    output.fluentd.fluent.io/enabled: "true"
spec: 
  outputs: 
  - kafka:
      brokers: my-cluster-kafka-bootstrap.default.svc:9091,my-cluster-kafka-bootstrap.default.svc:9092,my-cluster-kafka-bootstrap.default.svc:9093
      useEventTime: true
      defaultTopic: test